### PR TITLE
fix missing key error on init

### PR DESCRIPTION
**Pull request by vl-01**
this occurs with "Alloy Home" thermostat

### CODE REVIEW

**Comment by ZacheryThomas** [comment]
Thanks for your contribution!

It seems like different SmartRent setups send slightly different result back in terms of initial device data. 

If you don't mind, can you also run the code I pasted below and send me the output?

``` bash
python -c """
email = 'YOUR EMAIL HERE'
password = 'YOUR PASSWORD HERE'

SMARTRENT_BASE_URI     = 'https://control.smartrent.com/api/v2/'
SMARTRENT_SESSIONS_URI = SMARTRENT_BASE_URI + 'sessions'
SMARTRENT_HUBS_URI     = SMARTRENT_BASE_URI + 'hubs'
SMARTRENT_HUBS_ID_URI  = SMARTRENT_BASE_URI + 'hubs/{}/devices'

import requests
import json

res = requests.post(SMARTRENT_SESSIONS_URI, json={
    'email': email,
    'password': password
}).json()


token = res['access_token']
headers={
    'authorization': f'Bearer {token}'
}

hubs = requests.get(
    SMARTRENT_HUBS_URI,
    headers=headers
).json()

for hub in hubs:
    devices = requests.get(
        SMARTRENT_HUBS_ID_URI.format(hub['id']),
        headers=headers
    ).json()

    output = json.dumps(devices, indent=4)
    print(output)
"""
```

**Comment by ZacheryThomas** [comment]
I'll merge the code and make a new release later tonight.

**Comment by vl-01** [comment]
Sure, here it is:
```
[
    {
        "attributes": [
            {
                "name": "access_codes_supported",
                "state": "true"
            },
            {
                "last_read_at": "2022-01-21T23:56:42Z",
                "name": "notifications",
                "state": "KEY_OR_THUMBTURN_LOCK"
            },
            {
                "last_read_at": "2022-01-21T23:56:42Z",
                "name": "locked",
                "state": "true"
            }
        ],
        "battery_level": 96,
        "battery_powered": true,
        "icon": null,
        "id": 9999999,
        "inserted_at": "2021-09-05T02:26:07",
        "name": "Front Door - Lock",
        "online": true,
        "pending_update": false,
        "primary_lock": true,
        "room": {
            "hub_id": 999999,
            "icon": null,
            "id": 999999,
            "inserted_at": "2021-09-05T02:25:04.853981",
            "name": "No Room",
            "updated_at": "2021-09-05T02:25:04.853981"
        },
        "show_on_dashboard": true,
        "type": "entry_control",
        "updated_at": "2022-01-21T21:31:47",
        "valid_config": true,
        "warning": false
    },
    {
        "attributes": [
            {
                "last_read_at": "2022-01-22T03:08:21Z",
                "name": "mode",
                "state": "off"
            },
            {
                "last_read_at": "2022-01-20T13:59:09Z",
                "name": "heating_setpoint",
                "state": "77"
            },
            {
                "last_read_at": "2022-01-22T03:37:42Z",
                "name": "current_temp",
                "state": "72"
            },
            {
                "last_read_at": "2021-09-10T20:30:18Z",
                "name": "NOT_MAPPED_AWAY_HEATING",
                "state": "50.0"
            },
            {
                "last_read_at": "2021-09-10T20:30:18Z",
                "name": "NOT_MAPPED_ENERGY_SAVE_HEATING",
                "state": "62.0"
            }
        ],
        "battery_level": null,
        "battery_powered": false,
        "icon": null,
        "id": 9999999,
        "inserted_at": "2021-09-10T20:29:35",
        "name": "Thermostat ",
        "online": true,
        "pending_update": false,
        "primary_lock": false,
        "room": {
            "hub_id": 999999,
            "icon": null,
            "id": 999999,
            "inserted_at": "2021-09-05T02:25:04.853981",
            "name": "No Room",
            "updated_at": "2021-09-05T02:25:04.853981"
        },
        "show_on_dashboard": true,
        "type": "thermostat",
        "updated_at": "2021-12-13T23:22:48",
        "valid_config": true,
        "warning": false
    }
]
```

**Comment by ZacheryThomas** [comment]
Thanks for the comment!

For what its worth, my thermostat ends up sending something like this:

```json
{
    "attributes": [
        {
            "last_read_at": "2022-01-21T14:01:41Z",
            "name": "heating_setpoint",
            "state": "70"
        },
        {
            "last_read_at": "2022-01-21T14:01:36Z",
            "name": "mode",
            "state": "heat"
        },
        {
            "last_read_at": "2022-01-21T12:28:38Z",
            "name": "cooling_setpoint",
            "state": "76"
        },
        {
            "last_read_at": "2022-01-15T19:57:20Z",
            "name": "fan_mode",
            "state": "auto"
        },
        {
            "last_read_at": "2022-01-21T13:48:16Z",
            "name": "current_humidity",
            "state": "45"
        },
        {
            "last_read_at": "2022-01-21T12:28:47Z",
            "name": "current_temp",
            "state": "68"
        }
    ],
    "battery_level": null,
    "battery_powered": false,
    "icon": null,
    "id": xxxxxx,
    "inserted_at": "2021-07-12T14:05:16",
    "name": "Thermostat ",
    "online": true,
    "pending_update": false,
    "primary_lock": false,
    "room": {
        "hub_id": xxxxxx,
        "icon": null,
        "id": xxxxxx,
        "inserted_at": "2021-07-12T13:56:28.483753",
        "name": "No Room",
        "updated_at": "2021-07-12T13:56:28.483753"
    },
    "show_on_dashboard": true,
    "type": "thermostat",
    "updated_at": "2021-12-21T16:31:03",
    "valid_config": true,
    "warning": false
}
```

Kinda strange that things aren't that uniform

**Comment by vl-01** [comment]
No problem. It looks like my thermostat just lacks those capabilities. Except for the new ones, most apartment buildings in my city don't have central cooling.

**Comment by vl-01** [comment]
Thanks for your work reversing this stuff, btw. The SmartRent app has insurmountable usability problems for me; this API is by far the easiest method of controlling these devices that I've come across.

**Comment by ZacheryThomas** [comment]
I'm glad to hear that this API is working out for you!

Have you heard about / looked into Home Assistant before? Thats what I normally use to control most of my smarthome devices. I wrote a little integration for that so you can control your smartrent stuff though that UI as well

**Comment by vl-01** [comment]
I had tried it and was very impressed overall, but I wasn't able to get sufficiently fine-grained control over the cameras (I have to keep two video streams in correspondence so that I can do motion-triggered object detection while keeping resource usage to a minimum on a pi). But I might go back to it, if I can ever get around to wrapping the camera stuff in a Home Assistant plugin.

**Comment by ZacheryThomas** [comment]
Ahh nice. My setup is pretty simple and my PI still struggles sometimes lol.

**Pull request merged**
